/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../app/app.component';
const styles_AppComponent:any[] = ([] as any[]);
export const RenderType_AppComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted((null as any),[' Welcome to Synechron Pvt. Ltd'])),(_l()(),i0.ɵeld(0,
      (null as any),(null as any),0,'hr',([] as any[]),(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),1,'h5',([] as any[]),(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['Core Development Center, Pune']))],
      (null as any),(null as any));
}
export function View_AppComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'my-app',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i0.ɵdid(49152,(null as any),0,i1.AppComponent,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const AppComponentNgFactory:i0.ComponentFactory<i1.AppComponent> = i0.ɵccf('my-app',
    i1.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovc3luZWNocm9uLW5nNC10cmFpbmluZy0xNjE5Ni9uZzQtd2VicGFjay1ib290c3RyYXBwaW5nLWFvdC9hcHAvYXBwLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9zeW5lY2hyb24tbmc0LXRyYWluaW5nLTE2MTk2L25nNC13ZWJwYWNrLWJvb3RzdHJhcHBpbmctYW90L2FwcC9hcHAuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovc3luZWNocm9uLW5nNC10cmFpbmluZy0xNjE5Ni9uZzQtd2VicGFjay1ib290c3RyYXBwaW5nLWFvdC9hcHAvYXBwLmNvbXBvbmVudC50cy5BcHBDb21wb25lbnQuaHRtbCIsIm5nOi8vL0M6L3N5bmVjaHJvbi1uZzQtdHJhaW5pbmctMTYxOTYvbmc0LXdlYnBhY2stYm9vdHN0cmFwcGluZy1hb3QvYXBwL2FwcC5jb21wb25lbnQudHMuQXBwQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGgxPiBXZWxjb21lIHRvIFN5bmVjaHJvbiBQdnQuIEx0ZDwvaDE+PGhyPjxoNT5Db3JlIERldmVsb3BtZW50IENlbnRlciwgUHVuZTwvaDU+IiwiPG15LWFwcD48L215LWFwcD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBLHdFQUFJO2FBQUEsb0RBQW1DO01BQUE7TUFBQSw0Q0FBSTtNQUFBO01BQUEsOEJBQUk7Ozs7b0JDQS9DO01BQUE7YUFBQTs7OzsifQ==
